@HostAddress = http://localhost:5000

# GET /api/health
GET {{HostAddress}}/api/health
Accept: application/json

###

# GET /api/weather/all
GET {{HostAddress}}/api/weather/all
Accept: application/json

###

# POST /api/weather
POST {{HostAddress}}/api/weather
Content-Type: application/json

{
  "city": "Barcelona",
  "temperature": 26.5
}

###

# POST /api/weather validation error
POST {{HostAddress}}/api/weather
Content-Type: application/json

{
  "city": "",
  "temperature": 150
}
###
